"use client";

import { useState, useEffect, useCallback } from "react";
import { useQuery } from "convex/react";
// 🌟 FIX: Point this directly to your backend's autogenerated file!
import { api } from "convex/_generated/api";

export function useTimeSync() {
  const initialClientTime = typeof window !== "undefined" ? Date.now() : 0;

  const syncData = useQuery(api.timeattack.syncClock, {
    clientTime: initialClientTime,
  });

  const [offset, setOffset] = useState<number>(0);
  const [latency, setLatency] = useState<number>(0);

  useEffect(() => {
    if (!syncData) return;

    const t3 = Date.now();

    const rtt = t3 - syncData.clientTime;
    const currentLatency = rtt / 2;
    const currentOffset =
      syncData.serverTime - (syncData.clientTime + currentLatency);

    setLatency(currentLatency);
    setOffset(currentOffset);

    console.log(
      `[TimeSync Engine] Synchronized. Offset: ${currentOffset}ms, Latency: ${currentLatency}ms`,
    );
  }, [syncData]);

  return {
    offset,
    latency,
    getSyncedTime: useCallback(() => Date.now() + offset, [offset]),
  };
}
